django_rest_framework/django_rest_framework/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from auth import views as authviews
from rest_framework import routers

from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'users', authviews.UserViewSet)
router.register(r'groups', authviews.GroupViewSet)

urlpatterns = [
    # 'r' : regular expression
    # '^' : beginning
    # '$' : ending 
    # so r'^$' means when requested to individual app path, for example, 
    # http://127.0.0.1:8000/
	url(r'^', include(router.urls)),
    url(r'^admin/', admin.site.urls),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),    
    url(r'^example_api/', include('example_api.urls')),
    url(r'^samplepage/', include('samplepage.urls')),
    url(r'^music/', include('music.urls')),
    url(r'^hospital_recommend_api/', include('hospital_recommend_api.urls')),
    url(r'^knearest_api/', include('knearest_api.urls')),
]

# if debug mode(developer env)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_rest_framework/hospital_recommend_api/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'hospital_recommend_api'	# namespace of this urls.py

urlpatterns = [
	url(r'^$', views.index, name="index"),	
	url(r'^hospital_recommend_api/$', views.HospitalRecommend.as_view(), name="hospital_recommend_api"),
]

urlpatterns = format_suffix_patterns(urlpatterns)

django_rest_framework/music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'	# namespace of this urls.py


urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name="index"),	

	# 
	url(r'^register/$', views.UserFormView.as_view(), name="register"),	

	# /music/2/ 	album detail page id 2	
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'), 

	# /music/album/add/ 	to create album
	url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'), 

	# /music/album/2/ 		to update album id 2
	url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'), 

	# /music/album/2/delete/ to delete album id 2
	url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'), 		
]


# ###############################################################
# Deplicate code: Only for understand detail
# ###############################################################
# urlpatterns = [
# 	# /music/ :this is default homepage(index)
# 	url(r'^$', views.index, name="index"),		
#
# 	# /music/<album_id>/ :when <album_id> represent album_id that is a number ie: 1, 2, 500
# 	url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'), 
#
# 	# /music/<album_id>/favorite/ 
# 	url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'), 
# ]

django_rest_framework/hospital_recommend_api/models.py
from django.db import models

# Create your models here.

django_rest_framework/music/models.py
from django.db import models
from django.core.urlresolvers import reverse 

class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.FileField(max_length=1000)		# FileField to keep files

	# method for CreateView
	def get_absolute_url(self):
		print(f"....CreateView at primary key: {self.pk}....")
		# pass primary key to detail page 
		return reverse('music:detail', kwargs={'pk': self.pk}) 

	# str dunder"(double underscore) methods: 
	# represent to string of this object
	def __str__(self):
		return self.album_title + ' - ' + self.artist

class Song(models.Model):
	# ForeignKey: link Song to Album database index
	# models.CASCADE: when delete Album then delete Song that linked to that Album 
	album = models.ForeignKey(Album, on_delete=models.CASCADE)	
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return f"{self.song_title}.{self.file_type} / {self.album.artist}"

django_rest_framework/hospital_recommend_api/views.py
from django.shortcuts import render

from django.views import generic

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

# # Create your views here.
# class IndexView(generic.ListView):
# 	template_name = 'hospital_recommend_api/index.html' # plugin template
# 	# context_object_name = 'all_albums' # overide default get_queryset return variable name: 
# 	# 								   # 'object_list' to 'all_albums' that pass to template_name('hospital_recommend_api/index.html') 

# 	def get_queryset(self):
# 		return null=True

def index(request):
	return render(request, 'hospital_recommend_api/index.html')

	#all_albums = Album.objects.all()	# Use api to get all object in Album database 
	#return render(request, 'hospital_recommend_api/index.html', {'all_albums': all_albums,})		

	#### same as
	# all_albums = Album.objects.all()	# Use api to get all object in Album database 
	# template = loader.get_template('hospital_recommend_api/index.html')
	# context = {
	# 	'all_albums': all_albums,
	# }
	# return HttpResponse(template.render(context, request))


class HospitalRecommend(APIView):
    def get(self, request, *args, **kw):
        print("calling get method of HospitalRecommend")
        # Any URL parameters get passed in **kw
        result = {"hello": "123456"}
        response = Response(result, status=status.HTTP_200_OK)
        return response

    def post(self, request, *args, **kw):
        print("calling post method of HospitalRecommend")
        data = request.data
        pred = data
        result = {"result": pred}
        response = Response(result, status=status.HTTP_200_OK)
        return response  


django_rest_framework/hospital_recommend_api/templates/hospital_recommend_api/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a new Album{% endblock title %}
{% block album_active %}active{% endblock album_active %}

{% block body %}
<div class="container-fluid">
	<div cass="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>Add a New Album</h3>
					{% if error_message %}
						<p><strong>{{ error_message }}</strong></p>
					{% endif %}					
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include "music/form-template.html" %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>

					</form>
				</div>
			</div>
		</div>
	<div>

{% endblock body %}

django_rest_framework/hospital_recommend_api/templates/hospital_recommend_api/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>
		{% block title %}
		HOSPITAL RECOMMENDER API		{# default value #}
		{% endblock title %}
	</title>
	{% load staticfiles %}	<!-- Loads the path to static files: hospital_recommend_api/static -->
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" >
	<link href="https://fonts.googleapis.com/css?family=Itim" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{%  static 'hospital_recommend_api/style.css' %}">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

	<script src="{% static 'hospital_recommend_api/js/main.js' %}"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<!-- Header -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>	
				<span class="icon-bar"></span>	
				<span class="icon-bar"></span>	
			</button>
			<a class="navbar-brand" href="{% url 'hospital_recommend_api:index' %}">DocTr</a>
		</div>

		<!-- Items -->
		<div class="collapse navbar-collapse" id="topNavBar">
			<ul class="nav navbar-nav">
				<li class="">
					<a href="{% url 'hospital_recommend_api:index' %}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; HOME
					</a>
				</li>
				<li class="">
					<a href="{% url 'hospital_recommend_api:index' %}">
						<span class="glyphicon glyphicon-hospital_recommend_api" aria-hidden="true"></span>&nbsp; Recommender
					</a>
				</li>				
			</ul>

			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">					
				</div>	
				<button type="submit" class="btn btn-default">Search</button>
			</form>

			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Register
					</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
					</a>
				</li>						
			</ul>

		</div>

	</dir>
</nav>
{% block body %}
{% endblock body %}
</body>
</html>

django_rest_framework/hospital_recommend_api/templates/hospital_recommend_api/detail.html
{% extends 'hospital_recommend_api/base.html' %}
{% block title %}{{ album }}{% endblock title %}
{% block albums_active %}active{% endblock albums_active %}

{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'hospital_recommend_api:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }} <small>{{ album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'hospital_recommend_api:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.song_title }}</td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock body %}








<!-- Backup UI version 0.1 -->
<!-- { % extends 'hospital_recommend_api/base.html' %}

{ % block title %}
	{{ album.album_title }} by {{ album.artist }}
{ % endblock title %}

{ % block body %}

	<img src="{{ album.album_logo }}" style="width: 250px;">
	
	<h1>{{ album.album_title }}</h1>
	<h3>{{ album.artist }}</h3>

	{% if error_message	%}
		<p><strong>{{ error_message }}</strong></p>
	{% endif %}

	{% for song in album.song_set.all %}
		{{ song.song_title }}.{{ song.file_type }}
		{% if song.is_favorite	%}
			<img src="http://i.imgur.com/b9b13Rd.png" />
		{% endif %}	
		<br>	
	{% endfor %}

{ % endblock body %} -->

	<!-- Backup -->
	<!-- Deplicate: only for example, not proper way to favorite songs  -->
	<!-- https://www.blognone.com/node/37959 -->
	<!-- <form action="{% url 'hospital_recommend_api:favorite' album.id %}" method="post">
		{% csrf_token %}	
		{% for song in album.song_set.all %}
			<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
			<label for="song{{ forloop.counter }}">
				{{ song.song_title }}
				{% if song.is_favorite	%}
					<img src="http://i.imgur.com/b9b13Rd.png" />
				{% endif %}
			</label><br>
		{% endfor %}
		<input type="submit" value="Favorite">
	</form> -->

django_rest_framework/hospital_recommend_api/templates/hospital_recommend_api/form-template.html
{% for field in form %}
	<div class="form-group">
		<div class="col-sm-offet-2 col-sm-10">
			<span class="col-sm-10 text-danger small">{{ field.errors }}</span>
		</div>
		<br>
		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }}</div>
	</div>	
{% endfor %}

django_rest_framework/hospital_recommend_api/templates/hospital_recommend_api/index.html
{% extends 'hospital_recommend_api/base.html' %}
{% block albums_active %}active{% endblock albums_active %}

{% block body %}
<div class="container-fluid">
    <!-- Input -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Hello {{ user.username }}</h3>
        </div>

        <form action=# method="post" style="display: inline;">
            {% csrf_token %}
            <input type="hidden" name="album_id" value="xxx" />
            <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-trash"></span>
            </button>
        </form>
        

    </div>

</div>

{% endblock body %}

django_rest_framework/hospital_recommend_api/templates/hospital_recommend_api/registration_form.html
{% extends 'musichospital_recommend_api/base.html' %}
{% block title %}Register{% endblock title %}
{% block album_active %}active{% endblock album_active %}

{% block body %}
<div class="container-fluid">
	<div cass="row">
		<div class="col-sm-12 col-md-7">
			<div class="panel panel-default">
				<div class="panel-body">
					<h3>Create a New Account</h3>
					{% if error_message %}
						<p><strong>{{ error_message }}</strong></p>
					{% endif %}
					<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
						{% include "musichospital_recommend_api/form-template.html" %}
						<div class="form-group">
							<div class="col-sm-offset-2 col-sm-10">
								<button type="submit" class="btn btn-success">Submit</button>
							</div>
						</div>

					</form>
				</div>
			</div>
		</div>
	<div>

{% endblock body %}